# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [5]:
import torch
x = torch.tensor([1,2,3])
torch.cuda.is_available
device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.tensor([1, 2, 3]).to(device)


ModuleNotFoundError: No module named 'torch'

### 2. Create a random tensor with shape `(7, 7)`.  

In [ ]:
import torch
random_tensor = torch.rand(7, 7)

print(random_tensor)


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
import torch
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)
tensor2_T = tensor2.T  
result = torch.matmul(tensor1, tensor2_T)
print(result)
print("Shape:", result.shape)


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
print(f"Number of testing samples: {len(X_test)}") 
print(f"Number of predictions made: {len(y_preds)}")
print(f"Predicted values:\n{y_preds}")


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
import torch
torch.manual_seed(0)
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)


torch.manual_seed(1234)

tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)
print(tensor_A, tensor_B)



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)


torch.manual_seed(1234)


tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

tensor_B_T = tensor_B.T


result = torch.matmul(tensor_A, tensor_B_T)


print(result, result.shape)


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

torch.manual_seed(1234)


tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)


tensor_B_T = tensor_B.T


result = torch.matmul(tensor_A, tensor_B_T)

max_value = result.max()
min_value = result.min()

print("Result:\n", result)
print("Maximum value:", max_value.item())
print("Minimum value:", min_value.item())



### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
import torch

# 1️⃣ تحديد الجهاز (GPU أو CPU)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# 2️⃣ تثبيت العشوائية
torch.manual_seed(1234)

# 3️⃣ إنشاء تينسورين عشوائيين (2x3) وإرسالهم للجهاز
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

# 4️⃣ عمل transpose للتاني علشان الضرب المصفوفي
tensor_B_T = tensor_B.T

# 5️⃣ إجراء الضرب المصفوفي
result = torch.matmul(tensor_A, tensor_B_T)

# 6️⃣ إيجاد القيم العظمى والصغرى ومواقعهم
max_value = result.max()
min_value = result.min()
max_index = result.argmax()
min_index = result.argmin()

print("Result:\n", result)
print("Maximum value:", max_value.item())
print("Minimum value:", min_value.item())
print("Index of maximum value:", max_index.item())
print("Index of minimum value:", min_index.item())



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
import torch

# 1️⃣ تثبيت العشوائية
torch.manual_seed(7)

# 2️⃣ إنشاء تينسور عشوائي بالشكل (1, 1, 1, 10)
tensor = torch.rand(1, 1, 1, 10)

# 3️⃣ إزالة الأبعاد اللي قيمتها 1
tensor_squeezed = tensor.squeeze()

# 4️⃣ طباعة النتائج
print(tensor, tensor.shape)
print(tensor_squeezed, tensor_squeezed.shape)
